Repository LayerZero-Labs/devtools, pull requests merged in 2024-03, with the labels that each got.

#434 🧹 Update retry logic & exclude typescript from the bundle
  .changeset/cool-spiders-ring.md
  packages/ua-devtools-evm-hardhat/package.json
  packages/ua-devtools-evm-hardhat/src/oapp/typescript/typescript.ts
  pnpm-lock.yaml
Labels: chore

#444 🧹 Enforce curly braces
  .eslintrc.json
  packages/create-lz-oapp/src/utilities/terminal.ts
  packages/devtools-evm-hardhat/src/config.ts
  packages/devtools-evm-hardhat/src/internal/assertions.ts
  packages/devtools-evm-hardhat/src/runtime.ts
  packages/devtools-evm-hardhat/src/tasks/deploy.ts
  packages/devtools-evm-hardhat/src/tasks/transactions/subtask.sign-and-send.ts
  packages/devtools-evm/src/errors/parser.ts
  packages/devtools/src/common/promise.ts
  packages/devtools/src/transactions/signer.ts
  packages/export-deployments/src/common/fs.ts
  packages/export-deployments/src/index.ts
  packages/io-devtools/src/language/plurals.ts
  packages/io-devtools/src/stdio/printer.ts
  packages/protocol-devtools/src/dvn/config.ts
  packages/protocol-devtools/src/endpointv2/config.ts
  packages/protocol-devtools/src/executor/config.ts
  packages/protocol-devtools/src/priceFeed/config.ts
  packages/ua-devtools-evm-hardhat/src/tasks/oapp/config.get.default.ts
  packages/ua-devtools-evm-hardhat/src/tasks/oapp/config.get.executor.ts
  packages/ua-devtools-evm-hardhat/src/tasks/oapp/config.get.ts
  packages/ua-devtools-evm-hardhat/src/utils/taskHelpers.ts
  packages/ua-devtools-evm/src/lzapp/sdk.ts
  packages/ua-devtools/src/lzapp/config.ts
  packages/ua-devtools/src/oapp/config.ts
  packages/verify-contract/src/common/abi.ts
  packages/verify-contract/src/common/config.ts
  packages/verify-contract/src/common/etherscan.ts
  packages/verify-contract/src/common/licenses.ts
  packages/verify-contract/src/common/logger.ts
  packages/verify-contract/src/common/url.ts
  packages/verify-contract/src/hardhat-deploy/config.ts
  tests/ua-devtools-evm-hardhat-test/test/__utils__/endpointV2.ts
  tests/ua-devtools-evm-hardhat-test/test/task/oapp/config.get.default.test.ts
  tests/ua-devtools-evm-hardhat-test/test/task/oapp/config.get.executor.test.ts
  tests/ua-devtools-evm-hardhat-test/test/task/oapp/config.get.test.ts
  tests/ua-devtools-evm-hardhat-test/test/task/oapp/config.init.test.ts
Labels: chore

#441 🧹 Update hardhat-deploy
  .changeset/metal-rats-fix.md
  examples/oapp/package.json
  examples/oft/package.json
  package.json
  packages/devtools-evm-hardhat/package.json
  packages/toolbox-hardhat/package.json
  packages/ua-devtools-evm-hardhat/package.json
  pnpm-lock.yaml
  tests/devtools-evm-hardhat-test/package.json
  tests/export-deployments-test/package.json
  tests/ua-devtools-evm-hardhat-test/package.json
  tests/ua-devtools-evm-hardhat-v1-test/package.json
Labels: chore

#450 🪲 Workflow triggers
  .github/workflows/on-develop.yaml
  .github/workflows/reusable-test.yaml
Labels: bug

#426 🪲 Use relative links
  README.md
Labels: documentation

#451 🧹 Make value attribute optional in enforced options
  .changeset/dry-humans-smash.md
  packages/ua-devtools/src/oapp/schema.ts
  packages/ua-devtools/src/oapp/types.ts
Labels: chore

#452 🧹 Make executorConfig and ulnConfig optional
  .changeset/popular-peaches-accept.md
  packages/ua-devtools/src/oapp/config.ts
  packages/ua-devtools/src/oapp/types.ts
Labels: chore

#459 🧹 Make lint-staged more explicit
  .eslintignore
  package.json
Labels: chore

#460 🧹 Silence the bigint-buffer warning
  .changeset/lucky-garlics-end.md
  Dockerfile
  package.json
  patches/bigint-buffer@1.1.5.patch
  pnpm-lock.yaml
Labels: chore

#461 🗞️ Sign transactions on different chains in parallel
  .changeset/mighty-tigers-beam.md
  .changeset/three-bobcats-hear.md
  packages/devtools/src/transactions/signer.ts
  packages/devtools/src/transactions/utils.ts
  packages/devtools/test/transactions/signer.test.ts
  packages/devtools/test/transactions/utils.test.ts
  tests/ua-devtools-evm-hardhat-test/test/oapp/config.test.ts
  tests/ua-devtools-evm-hardhat-test/test/task/oapp/wire.test.ts
Labels: enhancement

#453 🧹 Make properties of Uln302 config optional
  .changeset/tasty-cougars-tie.md
  packages/protocol-devtools-evm/src/endpointv2/sdk.ts
  packages/protocol-devtools-evm/src/uln302/sdk.ts
  packages/protocol-devtools-evm/test/uln302/sdk.test.ts
  packages/protocol-devtools/src/endpointv2/types.ts
  packages/protocol-devtools/src/uln302/types.ts
  packages/ua-devtools/src/oapp/types.ts
Labels: chore

#462 🗞️ Add docker compose spec generation functionality
  .changeset/hungry-scissors-report.md
  Dockerfile
  packages/devtools/package.json
  packages/devtools/src/docker/compose.ts
  packages/devtools/src/docker/index.ts
  packages/devtools/src/docker/types.ts
  packages/devtools/src/index.ts
  packages/devtools/test/docker/__snapshots__/compose.test.ts.snap
  packages/devtools/test/docker/compose.test.ts
  pnpm-lock.yaml
Labels: enhancement

#467 🧹 Better logging and errors [1/N]
  .changeset/brown-ducks-poke.md
  .changeset/happy-cars-glow.md
  packages/devtools-evm/src/omnigraph/sdk.ts
  packages/devtools/src/common/promise.ts
  packages/devtools/test/common/promise.test.ts
  packages/ua-devtools-evm/src/oapp/sdk.ts
Labels: chore

#471 🗞️ Add a utility to create anvil CLI options
  .changeset/sharp-cars-destroy.md
  packages/devtools-evm/package.json
  packages/devtools-evm/src/index.ts
  packages/devtools-evm/src/simulation/anvil.ts
  packages/devtools-evm/src/simulation/index.ts
  packages/devtools-evm/test/simulation/__snapshots__/anvil.test.ts.snap
  packages/devtools-evm/test/simulation/anvil.test.ts
  packages/toolbox-hardhat/package.json
  pnpm-lock.yaml
Labels: enhancement

#466 🧹 Add github actions reporter to jest
  packages/build-lz-options/jest.config.js
  packages/create-lz-oapp/jest.config.js
  packages/devtools-evm-hardhat/jest.config.js
  packages/devtools-evm/jest.config.js
  packages/devtools/jest.config.js
  packages/export-deployments/jest.config.js
  packages/io-devtools/jest.config.js
  packages/omnicounter-devtools-evm/jest.config.js
  packages/omnicounter-devtools/jest.config.js
  packages/protocol-devtools-evm/jest.config.js
  packages/protocol-devtools/jest.config.js
  packages/toolbox-hardhat/jest.config.js
  packages/ua-devtools-evm-hardhat/jest.config.js
  packages/ua-devtools-evm/jest.config.js
  packages/ua-devtools/jest.config.js
  packages/verify-contract/jest.config.js
  tests/devtools-evm-hardhat-test/jest.config.js
  tests/devtools-evm-test/jest.config.js
  tests/export-deployments-test/jest.config.js
  tests/ua-devtools-evm-hardhat-test/jest.config.js
  tests/ua-devtools-evm-hardhat-v1-test/jest.config.js
Labels: chore

#474 🗞️ Bits and pieces of types and configuration for localnet [3/N]
  .changeset/witty-toes-compare.md
  packages/devtools-evm-hardhat/src/simulation/types.ts
  packages/devtools-evm-hardhat/src/type-extensions.ts
  packages/devtools-evm/src/simulation/anvil.ts
  packages/devtools/src/docker/types.ts
Labels: enhancement

#475 🪲 Use default reporter instead of summary
  packages/build-lz-options/jest.config.js
  packages/create-lz-oapp/jest.config.js
  packages/devtools-evm-hardhat/jest.config.js
  packages/devtools-evm/jest.config.js
  packages/devtools/jest.config.js
  packages/export-deployments/jest.config.js
  packages/io-devtools/jest.config.js
  packages/omnicounter-devtools-evm/jest.config.js
  packages/omnicounter-devtools/jest.config.js
  packages/protocol-devtools-evm/jest.config.js
  packages/protocol-devtools/jest.config.js
  packages/toolbox-hardhat/jest.config.js
  packages/ua-devtools-evm-hardhat/jest.config.js
  packages/ua-devtools-evm/jest.config.js
  packages/ua-devtools/jest.config.js
  packages/verify-contract/jest.config.js
  tests/devtools-evm-hardhat-test/jest.config.js
  tests/devtools-evm-test/jest.config.js
  tests/export-deployments-test/jest.config.js
  tests/ua-devtools-evm-hardhat-test/jest.config.js
  tests/ua-devtools-evm-hardhat-v1-test/jest.config.js
Labels: bug

#486 🧹 Take RPC URLs from environment in examples
  .changeset/fair-cars-tie.md
  examples/oapp/hardhat.config.ts
  examples/oft/hardhat.config.ts
Labels: chore

#488 🧹 Remove unused build tsconfigs
  packages/devtools-evm-hardhat/package.json
  packages/devtools-evm-hardhat/tsconfig.build.json
  packages/devtools-evm/package.json
  packages/devtools-evm/tsconfig.build.json
  packages/protocol-devtools-evm/package.json
  packages/protocol-devtools-evm/tsconfig.build.json
Labels: chore

#489 🗞️ Add stateInterval to anvil options [5/N]
  .changeset/nasty-pillows-film.md
  packages/devtools-evm/src/simulation/anvil.ts
  packages/devtools-evm/test/simulation/anvil.test.ts
Labels: enhancement

#495 🗞️ Adjust simulation config logic for anvil [7/N]
  .changeset/dull-bananas-kiss.md
  packages/devtools-evm-hardhat/src/simulation/config.ts
  packages/devtools-evm-hardhat/test/simulation/config.test.ts
Labels: enhancement

#493 🧹 Update @LayerZero-Labs dependencies to 2.1.18
  .changeset/fifty-points-tap.md
  .changeset/odd-fireants-glow.md
  examples/oapp/package.json
  examples/oft/package.json
  package.json
  packages/build-lz-options/package.json
  packages/devtools-evm-hardhat/package.json
  packages/devtools-evm/package.json
  packages/devtools/package.json
  packages/devtools/test/omnigraph/__snapshots__/format.test.ts.snap
  packages/omnicounter-devtools-evm/package.json
  packages/omnicounter-devtools/package.json
  packages/protocol-devtools-evm/package.json
  packages/protocol-devtools/package.json
  packages/test-devtools-evm-foundry/package.json
  packages/test-devtools-evm-hardhat/package.json
  packages/test-devtools/package.json
  packages/toolbox-hardhat/package.json
  packages/ua-devtools-evm-hardhat/package.json
  packages/ua-devtools-evm/package.json
  packages/ua-devtools/package.json
  pnpm-lock.yaml
  tests/devtools-evm-hardhat-test/package.json
  tests/devtools-evm-test/package.json
  tests/export-deployments-test/package.json
  tests/ua-devtools-evm-hardhat-test/package.json
  tests/ua-devtools-evm-hardhat-v1-test/package.json
Labels: chore

#496 🗞️ Hardhat simulation tasks [8/N]
  .changeset/shaggy-kangaroos-own.md
  examples/oapp/.gitignore
  examples/oft/.gitignore
  packages/devtools-evm-hardhat/src/constants/tasks.ts
  packages/devtools-evm-hardhat/src/tasks/index.ts
  packages/devtools-evm-hardhat/src/tasks/simulation/index.ts
  packages/devtools-evm-hardhat/src/tasks/simulation/logs.ts
  packages/devtools-evm-hardhat/src/tasks/simulation/start.ts
  packages/devtools-evm-hardhat/src/tasks/simulation/stop.ts
  packages/toolbox-hardhat/src/index.ts
  tests/ua-devtools-evm-hardhat-test/.gitignore
Labels: enhancement

#497 🪲 Don't use printRecord in SDKs
  .changeset/wet-buckets-flash.md
  packages/protocol-devtools-evm/src/dvn/sdk.ts
  packages/protocol-devtools-evm/src/executor/sdk.ts
  packages/protocol-devtools-evm/src/priceFeed/sdk.ts
  packages/protocol-devtools-evm/src/uln302/sdk.ts
Labels: bug

#508 🧹 Custom configuration: Pass configLoader to config validator [1/N]
  packages/ua-devtools-evm-hardhat/src/tasks/oapp/config.get.ts
  packages/ua-devtools-evm-hardhat/src/tasks/oapp/enforced.opts.get.ts
  packages/ua-devtools-evm-hardhat/src/tasks/oapp/peers.get.ts
  packages/ua-devtools-evm-hardhat/src/tasks/oapp/wire/index.ts
  packages/ua-devtools-evm-hardhat/src/utils/taskHelpers.ts
Labels: chore

#509 🗞️ Configuration functions
  .changeset/selfish-ways-explode.md
  packages/io-devtools/src/config/loading.ts
  packages/io-devtools/test/config/__snapshots__/loading.test.ts.snap
  packages/io-devtools/test/config/loading.test.ts
Labels: enhancement

#517 🧹 Add prune script to wipe everything
  package.json
Labels: chore

#518 🧹 Re-export useful types from toolbox-hardhat; Fix small type & export issues
  .changeset/large-trains-change.md
  examples/oapp/layerzero.config.ts
  examples/oft/layerzero.config.ts
  packages/devtools/src/types.ts
  packages/devtools/test/omnigraph/types.test.ts
  packages/toolbox-hardhat/types/index.d.ts
  packages/ua-devtools-evm-hardhat/src/index.ts
Labels: enhancement
